"use strict";
// ============================== THE CITY ==============================
// Regions on one global tile grid. `ox`/`oy` are that region's origin in global
// TILES, and the whole city is laid out ONCE, up front, so no district ever has
// to move again — a region's origin is baked into every save's deltas and into
// SPAWN, and shifting one after it has content is the expensive mistake:
//
//        gx 0..35        gx 36..75          gx 76..111
//   gy    0..29  ·       THE TOWER DISTRICT · THE ANNEX
//   gy   30..59  THE FLATS · COURTHOUSE SQ  · THE STRAND
//   gy   60..89  ·       MOTOR ROW          · ·
//
// Everything is 30 tiles tall so the bands stack flush; unbuilt cells are solid
// by default, so a district whose neighbour does not exist yet simply has a wall
// there and gains an exit the day that neighbour lands. Openings are cut on both
// sides in advance — the courthouse already has its doors to The Flats and the
// Tower District, and they are walls until those regions arrive.
//
// Geometry is authored ONCE. `layers.street` and `layers.floor` dress it.
// `sub` rewrites tiles per layer; the rest is content.

export const REGIONS = [
  {
    id: 'courthouse',
    name: 'COURTHOUSE SQUARE',
    ox: 36, oy: 30,
    rows: [
      '##################################....##',
      '#......................................#',
      '#.....############################.....#',
      '#.....############################.....#',
      '#.....############################.....#',
      '#.....############################.....#',
      '#.....############################.....#',
      '#.....############################.....#',
      '#.....############################.....#',
      '#.....############################.....#',
      '#.....####www####wwww####www######.....#',
      '#.....############++++############.....#',
      '#.................ssss.................#',
      '#.................ssss.................#',
      '#.................ssss.................#',
      '#.......T.....T..........T.....T.......#',
      '#.........bb................bb.........#',
      '#...................k..................#',
      '#......................................#',
      '#......................................#',
      '========================================',
      '========================================',
      '----------------------------------------',
      '========================================',
      '#......................................#',
      '#.##############......###############..#',
      '#.#wwww####wwww#......##www####www###..#',
      '#.#####++#######......######++#######..#',
      '#......................................#',
      '#################....###################',
    ],
    layers: {
      street: {
        greet: 'COURTHOUSE SQUARE. Filing window closes at four. The steps are where the work is.',
        props: [
          { id: 'ch_in', tx: 19, ty: 11, spr: 'sign', repeat: true,
            into: 'dept13', spot: [12, 13],
            label: '[E] in through the doors',
            text: 'Through the doors, past the metal detector nobody is manning.' },
          { id: 'ch_doors', tx: 19, ty: 12, spr: 'sign',
            label: '[E] Superior Court — Dept. 13',
            text: 'SUPERIOR COURT — DEPARTMENT 13. The docket is posted behind glass, sun-bleached to the point of prophecy. Hon. M. BANE presiding. He has been presiding since before you were born.' },
          { id: 'ch_kiosk', tx: 20, ty: 17, spr: 'board', label: '[E] newsstand',
            text: 'The newsstand sells three papers, four lighters and a rack of business cards from attorneys who could afford the rack. Yours is not on it.' },
          { id: 'ch_bench', tx: 28, ty: 16, spr: 'sign', label: '[E] the bench nobody sits on',
            text: 'A brass plate on the backrest: IN MEMORY OF THOSE WHO SETTLED. Somebody has scratched an addendum: AND WERE RIGHT TO.' },
          { id: 'ch_window', tx: 22, ty: 12, spr: 'sign', label: '[E] the clerk\'s filing window',
            repeat: true,
            text: 'A slot, a bell, and a laminated sign reading NO EXCEPTIONS that has been laminated twice. Everything that is going to happen to anybody here goes through this slot first.' },
          { id: 'ch_bonds', tx: 8, ty: 27, spr: 'sign', repeat: true, tree: 'bonds',
            label: '[E] Ace Bail Bonds — 24 HRS',
            text: 'ACE BAIL BONDS — 24 HRS — SE HABLA ESPAÑOL. A hand-lettered addition: AND WE MEAN 24.' },
          // ---- the bleed ----
          { id: 'ch_bleed', tx: 30, ty: 18, spr: 'board', bleed: 1,
            label: '[E] the notice that is not a notice',
            text: 'A time-entry form, stapled to the kiosk post. Carbon, third sheet. Nobody in this county uses carbon. HOURS TO BE CHARGED is filled in. MATTER № is blank. The handwriting is yours.' },
          { id: 'ch_cross', tx: 15, ty: 12, spr: 'sign', repeat: true, cross: true, bleed: 2,
            who: 'THE DOOR BEHIND THE BENCH',
            label: '[E] the door that is not on the plan',
            text: 'There is a door four feet left of the courthouse steps. There has never been a door here. Fire-rated, wire-glass, county lever handle worn bright underneath. The wall it sits in is eleven feet of granite. Through the glass: a bench, the lights on, a matter in session.',
            fact: 'iry_door' },
        ],
        pickups: [
          { id: 'ch_flyer', tx: 8, ty: 18, spr: 'dossier', item: 'flyer',
            name: 'FLYER: NOTARY · TAXES · DIVORCE', note: 'Somebody else already had your idea. Their phone number is torn off. All of them.' },
          { id: 'ch_card', tx: 34, ty: 16, spr: 'dossier', item: 'card',
            name: "BONDSMAN'S CARD", note: 'A referral source, if you can stomach it. You can.' },
        ],
        npcs: [
          { id: 'hector', name: 'Hector', spr: 'hector', tx: 22, ty: 17,
            label: '[E] Hector (newsstand)' },
          { id: 'delgado', name: 'Arturo Delgado', spr: 'delgado', tx: 16, ty: 14,
            label: '[E] the man on the steps' },
          // Named in five places since Phase 1 and on the bench throughout.
          // He is on both layers at the same tile, because Department 13 is one
          // room and has been in session the entire time.
          { id: 'bane', name: 'Hon. M. Bane', spr: 'bane', tx: 17, ty: 13, bleed: 2,
            label: '[E] the judge on the steps' },
        ],
        actors: [
          { id: 'ch_civ1', type: 'civ', tx: 14, ty: 18 },
          { id: 'ch_civ2', type: 'civ', tx: 26, ty: 19 },
          { id: 'ch_srv1', type: 'server', tx: 34, ty: 22 },
          { id: 'ch_srv2', type: 'server', tx: 6, ty: 24 },
          { id: 'ch_depo', type: 'depo', tx: 30, ty: 13 },
          { id: 'ch_land', type: 'landlord', tx: 12, ty: 19 },
          { id: 'ch_you', type: 'yourself', tx: 24, ty: 14 },
        ],
      },
      floor: {
        // the trees are gone and the newsstand is a stump of itself
        sub: { T: 'x', k: 'x' },
        greet: 'COURTHOUSE SQUARE. No cars. No sun. Department 13 is lit, and it is in session.',
        // Where you wake up is on the lights already, and it is the only place
        // that is. You get one district free so you can learn what the panel
        // says before you are standing in front of one in the dark.
        litFree: true,
        lightCost: 0,
        props: [
          { id: 'ch_in', tx: 19, ty: 11, spr: 'sign', repeat: true,
            into: 'dept13', spot: [12, 13],
            label: '[E] in through the doors',
            text: 'Through the doors. There is no metal detector on this side and the frame it stood in is still bolted to the floor.' },
          { id: 'ch_doors', tx: 19, ty: 12, spr: 'sign',
            label: '[E] the docket behind the glass',
            text: 'The docket behind the glass lists one matter. It has listed one matter for a very long time. The caption is your name, and under COUNSEL FOR, also your name.',
            fact: 'unsent_docket' },
          { id: 'ch_kiosk', tx: 20, ty: 17, spr: 'board', label: '[E] what is left of the newsstand',
            text: 'The papers are still stacked. Every one of them is the same edition. You check four before you stop checking.' },
          { id: 'ch_panel', tx: 26, ty: 12, spr: 'board', repeat: true, lights: true,
            label: '[E] the lighting panel',
            text: 'A grey breaker panel set into the wall beside the steps, with a form taped over the switches at eye height — not a notice, a FORM, with a line for hours and a line for a matter number.' },
          // ---- the bleed ----
          { id: 'ch_bleed', tx: 30, ty: 18, spr: 'board', bleed: 1,
            label: '[E] the newsstand rack',
            text: 'One paper in the rack is a different edition from the other four hundred. Thin, warm, dated tomorrow. Page one: a fire on The Strand. Page four: a photograph of these steps at four in the afternoon, eleven people on them, in daylight, moving.' },
          { id: 'ch_cross', tx: 15, ty: 12, spr: 'sign', repeat: true, cross: true, bleed: 2,
            who: 'THE DOOR BEHIND THE BENCH',
            label: '[E] the door with the light under it',
            text: 'A door four feet left of the steps, in a wall that is granite the whole way through. There is light under it and the colour is wrong — not this building\'s ceilings. Afternoon light, low, and it moves the way light moves when traffic goes past.',
            fact: 'iry_door' },
        ],
        npcs: [
          { id: 'clerk', name: 'The Night Clerk', spr: 'clerk', tx: 21, ty: 13,
            label: '[E] the Night Clerk' },
          { id: 'bane', name: 'Hon. M. Bane', spr: 'bane', tx: 17, ty: 13, bleed: 2,
            label: '[E] the judge at the top of the steps' },
        ],
        pickups: [
          { id: 'ch_letter', tx: 20, ty: 16, spr: 'dossier', item: 'letter',
            name: 'AN UNSENT RESIGNATION LETTER', note: 'Not your handwriting. The date is blank. The signature line has been signed and scratched out eleven times.',
            fact: 'unsent_hand' },
        ],
        actors: [
          { id: 'ch_unb1', type: 'unbilled', tx: 33, ty: 18 },
          { id: 'ch_you', type: 'yourself', tx: 24, ty: 14 },
        ],
      },
    },
  },
  {
    id: 'strand',
    name: 'THE STRAND',
    ox: 76, oy: 30,
    rows: [
      '################....################',
      '#..................................#',
      '#.################################.#',
      '#.################################.#',
      '#.################################.#',
      '#.################################.#',
      '#.################################.#',
      '#.################################.#',
      '#.##wwww###wwww###wwww###wwww#####.#',
      '#.####++######++######++##########.#',
      '#.....T.........T.........T........#',
      '#..................................#',
      '#........bb..............bb........#',
      '#..................................#',
      '#.......####################.......#',
      '#.......####################.......#',
      '#.......###wwww###wwww###ww#.......#',
      '#.......#########++#########.......#',
      '#..................................#',
      '#..................................#',
      '===================================#',
      '===================================#',
      '-----------------------------------#',
      '===================================#',
      '#..................................#',
      '#.################################.#',
      '#.##wwww###wwww###wwww###wwww#####.#',
      '#.########++############++########.#',
      '#..................................#',
      '####################################',
    ],
    layers: {
      street: {
        greet: 'THE STRAND. Small business, small claims. Your office is the one over the Golden Wok.',
        props: [
          { id: 'st_office', tx: 17, ty: 17, spr: 'sign', repeat: true,
            into: 'suite2b', spot: [1, 7], needsOffice: true,
            label: '[E] up to Suite 2B',
            text: 'Up the stairs beside the Wok, past the smell.' },
          { id: 'st_buzzer', tx: 15, ty: 18, spr: 'sign',
            label: '[E] the buzzer',
            text: 'A strip of masking tape on the buzzer, and on the tape, in marker, your name. Under it someone has added ESQ. with a caret. You did not do that. You have decided to like it. Taped inside the glass, where a lease is required to be posted: GOLDEN WOK HOLDINGS LLC, LANDLORD.',
            fact: 'wok_landlord' },
          // Evicted, the stair is not yours and the day still has to end
          // somewhere. Blocking sleep would soft-lock the run: ending days is
          // how you get to the work that pays the arrears off.
          { id: 'st_car', tx: 20, ty: 18, spr: 'sign', repeat: true, office: true,
            needsOffice: false,
            label: '[E] the firm car',
            text: 'The car, with the files in the footwell and the seat as far back as it goes. The stairwell door has a different lock on it now. It took them four days.' },
          { id: 'st_board', tx: 6, ty: 13, spr: 'board', label: '[E] corkboard',
            text: 'LAUNDROMAT CORKBOARD: a lost cat, a bass amp, three tabs torn off a card that reads EVICTION? KNOW YOUR RIGHTS — and four staples in a rectangle, holding nothing. Whatever was posted there was county-yellow; there is a strip of it still under the left staple, and the printed date on it has not come yet.',
            fact: 'wok_notice' },
          { id: 'st_lease', tx: 26, ty: 18, spr: 'board', repeat: true, tree: 'lease',
            label: '[E] the lease, in the glass',
            text: 'Your own lease, posted in the glass by the stairwell because the code says it has to be. Eleven hundred a week for a room over a kitchen, on a form nobody drafted so much as assembled.',
            fact: 'lease_terms' },
          // ---- the bleed ----
          { id: 'st_bleed', tx: 10, ty: 19, spr: 'board', bleed: 1,
            label: '[E] the storefront between the two storefronts',
            text: 'Between the dry cleaner and the place that has been PERMANENTLY CLOSED for six years, a travel agency. Open. A fare board with prices that stopped being prices before you qualified, a wall map with the pins still in, a kettle on behind the counter. You have walked this block four hundred times. You cannot remember whether it was here.' },
        ],
        npcs: [
          { id: 'ruiz', name: 'Marisol Ruiz', spr: 'ruiz', tx: 8, ty: 12,
            label: '[E] the woman outside the laundromat' },
        ],
        pickups: [
          { id: 'st_rent', tx: 29, ty: 11, spr: 'dossier', item: 'rent',
            name: 'RENT NOTICE — DUE THE 1st', note: 'Eleven hundred, and the Wok is not negotiable about it.' },
        ],
        actors: [
          { id: 'st_civ1', type: 'civ', tx: 24, ty: 11 },
          { id: 'st_srv1', type: 'server', tx: 30, ty: 21 },
          { id: 'st_coll1', type: 'collections', tx: 12, ty: 19 },
          { id: 'st_land', type: 'landlord', tx: 20, ty: 24 },
        ],
      },
      floor: {
        sub: { T: 'x' },
        greet: 'THE STRAND. Every storefront is lit, and every storefront is a different year.',
        greetDark: 'THE STRAND. The storefronts are all still there. You cannot see into a single one of them, and they can presumably see out.',
        lightCost: 10,
        props: [
          { id: 'st_panel', tx: 3, ty: 19, spr: 'board', repeat: true, lights: true,
            label: '[E] the lighting panel',
            text: 'The same panel. The same form, in the same hand, taped at the same height — which means somebody walked the whole length of this street putting them up, and that somebody expected people to be working here.' },
          { id: 'st_office', tx: 17, ty: 17, spr: 'sign', repeat: true,
            into: 'suite2b', spot: [1, 7],
            label: '[E] SUITE 2B — the door is open',
            text: 'The door is open. It has been open the whole time.' },
          { id: 'st_board', tx: 6, ty: 13, spr: 'board', label: '[E] corkboard',
            text: 'The cork is furred with staples. Every notice has been taken down. The tabs are all still there — every phone number intact, nobody ever tore one off.' },
          { id: 'st_window1', tx: 12, ty: 10, spr: 'board', label: '[E] the first storefront',
            text: 'A travel agency. Card rack, wall map, a fare board with prices on it that stopped being prices in 1981, and a desk calendar open at a Thursday in a year you would have to work out. The lights are on. The kettle is warm.',
            fact: 'yr_first' },
          { id: 'st_window2', tx: 24, ty: 10, spr: 'board', label: '[E] the next storefront',
            text: 'Four doors down and eleven years later. Same street, same fittings, a computer with a beige screen and a phone with a cord — and through the glass at the far end of it, past the stockroom door, the travel agency again, from behind.',
            fact: 'yr_next' },
          { id: 'st_window3', tx: 30, ty: 28, spr: 'board', label: '[E] the last one on the row',
            text: 'This one is yours. Suite 2B, at street level, which it has never been, with a folding table in it and a cot you have decided not to describe as a cot — and a date on the wall calendar that is four years after the last time you were in it.',
            fact: 'yr_yours' },
          // ---- the bleed ----
          { id: 'st_bleed', tx: 10, ty: 19, spr: 'board', bleed: 1,
            label: '[E] the window with the weather in it',
            text: 'One pane on this street has something behind it. Not a lit room — an outside. A road, a kerb, a bus shelter advertising a firm you have never heard of, and rain coming down at an angle on all of it. The glass is cold, which nothing in this building is. A bus goes past. It is full of people going home.' },
        ],
        pickups: [
          { id: 'st_ledger', tx: 6, ty: 12, spr: 'dossier', item: 'ledger',
            name: 'A TIME LEDGER, STILL RUNNING', note: 'Entries in your hand, at six-minute intervals, for work you have not done yet.' },
        ],
        npcs: [
          { id: 'okonkwo', name: 'A. Okonkwo', spr: 'stayed', tx: 11, ty: 11,
            label: '[E] the one at the desk by the window' },
        ],
        actors: [
          { id: 'st_unb1', type: 'unbilled', tx: 20, ty: 18 },
          { id: 'st_unb2', type: 'unbilled', tx: 27, ty: 21 },
          { id: 'st_sty1', type: 'stayed', tx: 11, ty: 11 },
          { id: 'st_sty2', type: 'stayed', tx: 24, ty: 24 },
        ],
      },
    },
  },
  {
    id: 'tower',
    name: 'THE TOWER DISTRICT',
    ox: 36, oy: 0,
    rows: [
      '########################################',
      '#......................................#',
      '#...###################....##########..#',
      '#...###################....##########..#',
      '#...###################....##########..#',
      '#...###################....##www#www#..#',
      '#...##wwww##wwww##www##....##########..#',
      '#...###################....##########..#',
      '#...###################....##########..#',
      '#...###################....##www#www#..#',
      '#...##wwww##wwww##www##....##########..#',
      '#...###################....####++####..#',
      '#...###################................#',
      '#...########++#########................#',
      '#..........sssss.......................#',
      '#..........sssss.......................#',
      '#.......................................',
      '#.......................................',
      '#.......T.....T...........T.....T.......',
      '#..................bb..................#',
      '#......................................#',
      '#.....xxxxxxx.............xxxxxxxx.....#',
      '#......................................#',
      '#......................................#',
      '#.#############...................ssss.#',
      '#.##wwww#######...................ssss.#',
      '#.#############...................ssss.#',
      '#.#####++######...................ssss.#',
      '#.................................ssss.#',
      '##################################....##',
    ],
    layers: {
      street: {
        greet: 'THE TOWER DISTRICT. Dewey, Cheatham & Howe on the left, Grabbit & Runn on the right, and a plaza between them with nowhere to stand that is not overlooked.',
        props: [
          { id: 'tw_lobby', tx: 12, ty: 13, spr: 'sign', repeat: true,
            into: 'dch', spot: [10, 9],
            label: '[E] in through the doors',
            text: 'You know the weight of these doors in your shoulder.' },
          { id: 'tw_doors', tx: 13, ty: 16, spr: 'sign',
            label: '[E] DEWEY, CHEATHAM & HOWE',
            text: 'You know the weight of these doors in your shoulder. Posted inside the glass where a licence has to be posted, and where nobody has ever read it: the partnership agreement\'s covenant clause. Two years. Fifty miles. Any client of the firm, and CLIENT OF THE FIRM is defined at paragraph forty-one to include anyone the firm has ever opened a file on.',
            fact: 'dch_noncompete' },
          { id: 'tw_plaque', tx: 23, ty: 13, spr: 'sign', label: '[E] the plaza plaque',
            text: 'DEWEY PLAZA — DEDICATED 1971 — A PLACE FOR THE PUBLIC. It is a place for the public in the sense that the public may cross it.' },
          { id: 'tw_grabbit', tx: 31, ty: 11, spr: 'sign', repeat: true,
            into: 'grabbit', spot: [7, 7],
            label: '[E] GRABBIT & RUNN — reception',
            text: 'The other one. Identical inside, apparently, down to the carpet, which people say the way you\'d mention a coincidence and not a supplier.' },
          { id: 'tw_dock', tx: 7, ty: 28, spr: 'board', label: '[E] the loading dock',
            text: 'A grey van with the rear doors open and nothing written on it. Inside, four banker\'s boxes and a clipboard, and on the clipboard a list of names with tick-boxes, and one of the names is yours and the box beside it is not ticked.' },
          // ---- the bleed ----
          { id: 'tw_bleed', tx: 35, ty: 21, spr: 'board', bleed: 1,
            label: '[E] the eleventh floor',
            text: 'Count up eleven floors. One window lit in the whole elevation, at half past two in the afternoon, sun full on the glass. You should not be able to see anything through it. There is a desk at the window and somebody at the desk, and they have not moved in four minutes. A man going past asks if you are all right.' },
          { id: 'tw_cross', tx: 27, ty: 15, spr: 'sign', repeat: true, cross: true, bleed: 2,
            who: 'THE FIRE DOOR ON THE PLAZA',
            label: '[E] the fire door in the plaza wall',
            text: 'A fire door flush to the plaza wall, on the side where there is no building. It is a retaining wall. Behind it is eleven feet of fill and then Fourth Street. There is a push bar on this side, and push bars go on the side people get out from.',
            fact: 'iry_same' },
        ],
        pickups: [
          { id: 'tw_billing', tx: 3, ty: 20, spr: 'dossier', item: 'billing',
            name: 'A BILLING SUMMARY, INTERNAL',
            note: 'Not the client copy. Realisation rates by associate, four years, with the write-offs in a separate column and a note at the bottom about which of them to have the conversation with.',
            fact: 'dch_billing' },
          { id: 'tw_clause', tx: 26, ty: 16, spr: 'dossier', item: 'clause',
            name: 'A PAGE FROM THE PARTNERSHIP AGREEMENT',
            note: 'Clause 9. You signed this. You remember the pen and the room and the fact that nobody read it out, and you remember deciding that was normal.',
            fact: 'dch_clause9' },
        ],
        npcs: [
          { id: 'hargrove', name: 'Emmett Hargrove', spr: 'hargrove', tx: 17, ty: 17,
            label: '[E] Hargrove' },
        ],
        actors: [
          { id: 'tw_ret1', type: 'retrieval', tx: 9, ty: 22 },
          { id: 'tw_ret2', type: 'retrieval', tx: 12, ty: 23 },
          { id: 'tw_ret3', type: 'retrieval', tx: 6, ty: 23 },
          { id: 'tw_srv1', type: 'server', tx: 30, ty: 20 },
          { id: 'tw_coll1', type: 'collections', tx: 33, ty: 17 },
          { id: 'tw_depo1', type: 'depo', tx: 20, ty: 20 },
          { id: 'tw_boss', type: 'noncompete', tx: 19, ty: 17 },
        ],
      },
      floor: {
        sub: { T: 'x' },
        // The most expensive floor in the city, and the one you least want dark.
        lightCost: 20,
        greet: 'THE TOWER DISTRICT. Every window on both towers is lit. You have been on the other side of one of them.',
        greetDark: 'THE TOWER DISTRICT. This is where you woke up. It is not lit and you know the way anyway, which is the part you would rather not have found out.',
        props: [
          { id: 'tw_panel', tx: 33, ty: 25, spr: 'board', repeat: true, lights: true,
            label: '[E] the lighting panel',
            text: 'This one is not taped up. It is engraved, on a brass plate, at eye height, next to the lift call button — which means it was not an improvisation. It was specified.' },
          { id: 'tw_lobby', tx: 12, ty: 13, spr: 'sign', repeat: true,
            into: 'dch', spot: [10, 9],
            label: '[E] in through the doors',
            text: 'The doors are not locked. They were not locked the night you left either.' },
          { id: 'tw_desk', tx: 16, ty: 17, spr: 'sign', label: '[E] the desk',
            text: 'The desk you woke at is out here, in the plaza, at the correct angle to a window that is eleven floors up. The nameplate is yours. The coffee is still warm and the ring under it is forty years deep.',
            fact: 'tw_desk' },
          { id: 'tw_grabbit', tx: 31, ty: 11, spr: 'sign', repeat: true,
            into: 'grabbit', spot: [7, 7],
            label: '[E] GRABBIT & RUNN — reception',
            text: 'The other one, lit the same, at the same hour, on the same side of a plaza with nobody crossing it.' },
          { id: 'tw_file', tx: 13, ty: 16, spr: 'dossier', repeat: true, tree: 'personnel',
            label: '[E] the personnel file',
            text: 'Your personnel file, open, on a chair nobody is sitting in.',
            fact: 'tw_reviews' },
          // ---- the bleed ----
          { id: 'tw_bleed', tx: 35, ty: 21, spr: 'board', bleed: 1,
            label: '[E] the eleventh floor',
            text: 'Every window on both towers is lit, and one is lit differently. Eleven up, and what comes out of it is afternoon — the real kind, with an angle and dust in it. It lands on the plaza in a rectangle you can stand in. The rectangle has moved a foot to the left since you noticed it.' },
          { id: 'tw_cross', tx: 27, ty: 15, spr: 'sign', repeat: true, cross: true, bleed: 2,
            who: 'THE FIRE DOOR ON THE PLAZA',
            label: '[E] the fire door with the noise behind it',
            text: 'A fire door in the retaining wall, and behind it the sound of a street: engines, a horn a long way off, somebody\'s radio, a bus kneeling at a stop. You have not heard a vehicle since you woke up. You had not noticed that until now.',
            fact: 'iry_same' },
        ],
        pickups: [
          { id: 'tw_nameplate', tx: 20, ty: 18, spr: 'dossier', item: 'nameplate',
            name: 'A NAMEPLATE, FACE DOWN',
            note: 'On the back, scratched in with a compass point by somebody who had a lot of time at that desk: CL. 9 IS NOT ABOUT RETIREMENT.',
            fact: 'tw_ninth' },
        ],
        actors: [
          { id: 'tw_pj', type: 'past_junior', tx: 25, ty: 22 },
          { id: 'tw_pc', type: 'past_counsel', tx: 9, ty: 19 },
          { id: 'tw_pp', type: 'past_partner', tx: 18, ty: 16 },
          { id: 'tw_sty1', type: 'stayed', tx: 30, ty: 14 },
          { id: 'tw_sty2', type: 'stayed', tx: 20, ty: 28 },
          { id: 'tw_unb1', type: 'unbilled', tx: 24, ty: 27 },
        ],
      },
    },
  },
  {
    id: 'annex',
    name: 'THE ANNEX',
    ox: 76, oy: 0,
    // The only INTERIOR district: corridors and rooms, not streets. Two ways in
    // — up the stair from The Strand at the bottom, and west across the bridge
    // from the Tower District at rows 16-18.
    rows: [
      '######wwww####wwww####www###########',
      '#............................ssss..#',
      '#............................ssss..#',
      '#......bb.....bb.....bb......ssss..#',
      '#..................................#',
      '#......bb.....bb.....bb............#',
      '#..................................#',
      '#..................................#',
      '################++##################',
      '#..................................#',
      '#..................................#',
      '#..................................#',
      '#..................................#',
      '#..#####..#######################..#',
      '#..................................#',
      '#..###################..#########..#',
      '...................................#',
      '...###########..#################..#',
      '...................................#',
      '#..###..#########################..#',
      '#..................................#',
      '#..#################..###########..#',
      '#..................................#',
      '#..................................#',
      '#..................................#',
      '#.....#########..########..........#',
      '#...b........................b.....#',
      '#..................................#',
      '#..................................#',
      '################....################',
    ],
    layers: {
      street: {
        greet: 'THE ANNEX. Records. Nine floors of them, and this is the one they let the public into.',
        props: [
          { id: 'an_counter', tx: 16, ty: 26, spr: 'sign', repeat: true,
            label: '[E] the records counter',
            text: 'A counter nineteen feet long with one person behind it and a sign reading REQUESTS BEFORE 3PM taped over an older sign reading REQUESTS BEFORE 4PM taped over an older sign you cannot read.' },
          { id: 'an_index', tx: 6, ty: 14, spr: 'board', label: '[E] the index',
            text: 'Card index, forty drawers, still the only way to find anything because the terminal project was cancelled in a year the terminal is still displaying. Under D: DEWEY CHEATHAM & HOWE — see also ANNEX, CONSTRUCTION OF.',
            fact: 'an_index' },
          { id: 'an_stair', tx: 30, ty: 4, spr: 'sign', repeat: true,
            label: '[E] the stair down',
            text: 'SUBLEVELS A–C. AUTHORISED PERSONNEL. The chain across it has a padlock on it and the padlock has not been closed, and both of those facts have clearly been true for a very long time.' },
          { id: 'an_plaque', tx: 20, ty: 9, spr: 'sign', label: '[E] the dedication',
            text: 'THE ANNEX — GIFTED TO THE COUNTY BY DEWEY, CHEATHAM & HOWE, 1971. Below it, smaller: IN PERPETUITY. Below that, smaller still, and in a different metal: SUBJECT TO CLAUSE 9.',
            fact: 'an_gift' },
          // ---- the bleed ----
          { id: 'an_bleed', tx: 5, ty: 23, spr: 'board', bleed: 1,
            label: '[E] the run that is one run too many',
            text: 'The stacks in this room are lettered A to K, and there are twelve of them. You walk L end to end twice. Same length as the others, full, the cards in the same hand as every other card here. When you come out you are facing the counter. You went in facing the counter.' },
          { id: 'an_cross', tx: 24, ty: 16, spr: 'sign', repeat: true, cross: true, bleed: 2,
            who: 'THE END OF RUN L',
            label: '[E] the end of the run that should be a wall',
            text: 'Run L ends in a doorway. Not a fire exit, not a service door — a doorway with no door in it, cut square and finished, with a threshold strip worn through to the brass. Past it the shelving carries on, and the light on it is not this building\'s.',
            fact: 'iry_dept13' },
        ],
        pickups: [
          { id: 'an_ledger', tx: 33, ty: 20, spr: 'dossier', item: 'annex_ledger',
            name: 'A REQUEST LOG, 1971 TO DATE',
            note: 'Every record ever pulled from the sublevels, who pulled it, and when it went back. The column for WENT BACK is almost entirely empty and the ones that are filled in are all in the same hand.',
            fact: 'an_log' },
        ],
        npcs: [
          { id: 'ferris', name: 'Ferris', spr: 'ferris', tx: 15, ty: 26,
            label: '[E] the records clerk' },
        ],
        actors: [
          { id: 'an_civ1', type: 'civ', tx: 8, ty: 27 },
          { id: 'an_srv1', type: 'server', tx: 28, ty: 12 },
          { id: 'an_ret1', type: 'retrieval', tx: 20, ty: 4 },
          { id: 'an_coll1', type: 'collections', tx: 6, ty: 22 },
        ],
      },
      floor: {
        sub: { b: 'x' },
        // Deepest and dearest. DESIGN §7: Sublevel C is open.
        lightCost: 24,
        greet: 'THE ANNEX. Every drawer in the index is open. Somebody went through all forty of them and did not close one.',
        greetDark: 'THE ANNEX. The stacks go further back than the building does. You have checked this twice.',
        props: [
          { id: 'an_panel', tx: 18, ty: 27, spr: 'board', repeat: true, lights: true,
            label: '[E] the lighting panel',
            text: 'The oldest one you have seen. The form on it is not photocopied — it is carbon, and the carbon is on the third sheet, which means there were two above it, which means somebody was keeping a set.' },
          { id: 'an_stair', tx: 30, ty: 4, spr: 'sign', repeat: true,
            into: 'sublevel', spot: [14, 2],
            label: '[E] SUBLEVEL C — the chain is down',
            text: 'The chain is on the floor. The stair goes down further than three floors and the air coming up it is warm and smells of toner.',
            fact: 'an_sublevel' },
          { id: 'an_index', tx: 6, ty: 14, spr: 'board', label: '[E] the index',
            text: 'Forty drawers, all open. You go to D expecting the firm and find instead four hundred cards, one per name, each with a date of joining and a blank where a leaving date goes. Yours is filed under the year you were born.',
            fact: 'an_cards' },
          { id: 'an_boxes', tx: 33, ty: 20, spr: 'dossier', repeat: true, tree: 'annexboxes',
            label: '[E] the boxes at the end of the run',
            text: 'Four hundred banker\'s boxes, and the lids are off.',
            fact: 'an_boxes' },
          // ---- the bleed ----
          { id: 'an_bleed', tx: 5, ty: 23, spr: 'board', bleed: 1,
            label: '[E] the drawer that has been closed',
            text: 'Forty drawers in the index, all of them open. One is shut. Inside, filed correctly between two cards in the hand that wrote the other four hundred: a library card expiring in a year that has not happened, in a name on none of the other cards. And a receipt from a hardware shop on The Strand. One padlock, cash, 4:51 p.m.' },
          { id: 'an_cross', tx: 24, ty: 16, spr: 'sign', repeat: true, cross: true, bleed: 2,
            who: 'THE END OF RUN L',
            label: '[E] the doorway at the end of the run',
            text: 'Run L ends in a doorway with no door in it, brass threshold worn through in the middle. Past it: the same shelving, in daylight. A public terminal with a screensaver on, a chair pushed in, somebody\'s cardigan over the back of it.',
            fact: 'iry_dept13' },
        ],
        npcs: [
          { id: 'ferris', name: 'Ferris', spr: 'ferris', tx: 15, ty: 26,
            label: '[E] the clerk at the counter' },
        ],
        actors: [
          { id: 'an_sty1', type: 'stayed', tx: 10, ty: 10 },
          { id: 'an_sty2', type: 'stayed', tx: 26, ty: 22 },
          { id: 'an_sty3', type: 'stayed', tx: 8, ty: 6 },
          { id: 'an_unb1', type: 'unbilled', tx: 20, ty: 16 },
          { id: 'an_unb2', type: 'unbilled', tx: 12, ty: 24 },
          { id: 'an_boss', type: 'thefirm', tx: 30, ty: 6 },
        ],
      },
    },
  },
  {
    id: 'flats',
    name: 'RIVERSIDE / THE FLATS',
    ox: 0, oy: 30,
    rows: [
      '~~~#################################',
      '~~~,...............................#',
      '~~~,...............................#',
      '~~~,..#############....###########.#',
      '~~~,..#############....###########.#',
      '~~~,..#############....###########.#',
      '~~~,..#############....###########.#',
      '~~~,..#############....###########.#',
      '~~~,..#############....#www##www##.#',
      '~~~,..##wwww##www##....####++#####.#',
      '~~~,..#####++######................#',
      '~~~,...............................#',
      '~~~,....T.......T.........T........#',
      '~~~,......bb............bb.........#',
      '~~~,...............................#',
      '~~~,.,,,,,,,,,,,...................#',
      '~~~,.,,T,,,,,,,,...................#',
      '~~~,.,,,,,,,,,,,...................#',
      '~~~,.,,,,,,,,T,,...................#',
      '~~~,.,,,,,,,,,,,...................#',
      '~~~,================================',
      '~~~,================================',
      '~~~,--------------------------------',
      '~~~,================================',
      '~~~,...............................#',
      '~~~,.###########....##############.#',
      '~~~,.#wwww##ww##....##wwww###wwww#.#',
      '~~~,.####++#####....#####++#######.#',
      '~~~,...............................#',
      '~~~#################################',
    ],
    layers: {
      street: {
        greet: 'RIVERSIDE. Everybody calls it The Flats and nobody calls it Riverside, including the river.',
        props: [
          { id: 'fl_centre', tx: 12, ty: 11, spr: 'sign', repeat: true, tree: 'centre',
            label: '[E] the community centre — notices',
            text: 'A glass case by the doors, and behind the glass, thirty photocopies of the same three-day notice with thirty different apartment numbers written in by hand. Served Saturday. There is no proof of service on any of them and a three-day notice served on a Saturday is not a three-day notice.',
            fact: 'flats_notices' },
          { id: 'fl_sale', tx: 27, ty: 10, spr: 'board', label: '[E] the sign on the fence',
            text: 'A realtor\'s board, zip-tied over an older one that has not been taken down: 34 UNITS · DELIVERED VACANT · IN ESCROW. Somebody has put a fist through DELIVERED and it has been repaired with packing tape, from the inside.',
            fact: 'flats_sale' },
          { id: 'fl_river', tx: 4, ty: 17, spr: 'sign', repeat: true, label: '[E] the bank',
            text: 'The river, moving at about the speed of a document. This is the only part of the city where you can stand and not be able to see the Tower District, and everybody down here knows exactly where to stand.' },
          // ---- the bleed ----
          { id: 'fl_bleed', tx: 30, ty: 14, spr: 'board', bleed: 1,
            label: '[E] the chairs, stacked',
            text: 'Thirty stacking chairs against the community centre wall, out in the weather, which nobody down here would leave them in. You count them twice. The top one has a coat over it. The coat is dry. It has been raining since eleven.' },
        ],
        pickups: [
          { id: 'fl_ordinance', tx: 8, ty: 16, spr: 'dossier', item: 'ordinance',
            name: 'CITY ORD. 41-7 — RELOCATION ASSISTANCE',
            note: 'Photocopied so many times the seal is a grey smudge. Any tenant displaced by a sale is owed relocation. Nobody in that glass case has been told.',
            fact: 'flats_relocation' },
        ],
        npcs: [
          { id: 'iris', name: 'Iris Nakamura', spr: 'iris', tx: 14, ty: 12,
            label: '[E] the woman with the clipboard' },
          { id: 'halloran', name: 'W. Halloran', spr: 'halloran', tx: 28, ty: 24,
            label: '[E] the man in the good coat' },
        ],
        actors: [
          { id: 'fl_civ1', type: 'civ', tx: 20, ty: 12 },
          { id: 'fl_civ2', type: 'civ', tx: 9, ty: 24 },
          { id: 'fl_srv1', type: 'server', tx: 30, ty: 18 },
          { id: 'fl_chase', type: 'chaser', tx: 31, ty: 24 },
        ],
      },
      floor: {
        sub: { T: 'x' },
        // DESIGN §7: the only place on THE FLOOR with daylight. It is also the
        // only district that costs nothing to light, and those are the same
        // fact — the building never owned this one, so it has nothing to bill.
        litFree: true,
        lightCost: 0,
        daylight: true,
        greet: 'THE FLATS. There is daylight here. You have not seen the sun and there is no sun, and the light is on the buildings all the same, and it is warm.',
        props: [
          { id: 'fl_centre', tx: 12, ty: 11, spr: 'sign', label: '[E] the community centre — the doors are open',
            text: 'The glass case is empty and clean. Inside, the big room, and in the big room thirty chairs set out in a circle with the gap left at the near side the way you leave it for whoever is still coming. The room is warm. Nothing in this building is warm.',
            fact: 'flats_chairs' },
          { id: 'fl_river', tx: 4, ty: 17, spr: 'sign', repeat: true, label: '[E] the bank',
            text: 'The river is moving. You watch it for a while to be sure, because nothing else in this city has moved since you woke up, and it keeps moving the entire time you watch it.',
            fact: 'flats_sun' },
          { id: 'fl_warm', tx: 16, ty: 12, spr: 'sign', repeat: true, tree: 'warm',
            label: '[E] the back room',
            text: 'Behind the big room, a smaller one, warmer than the big one, with a kettle that has been recently used and thirty-one mugs on a draining rack.',
            fact: 'warm_room' },
          { id: 'fl_sale', tx: 27, ty: 10, spr: 'board', label: '[E] the board on the fence',
            text: 'The realtor\'s board is gone. Underneath it, the older one it was zip-tied over, which nobody ever took down and which reads: TENANTS COUNCIL MEETS THURSDAYS 7PM ALL WELCOME · SE HABLA ESPAÑOL · CHILDCARE.' },
          // ---- the bleed ----
          // The one district where the bleed is not frightening, because it is
          // the one district the building never had. What comes through here is
          // people, and they are fine, and they are not thinking about you.
          { id: 'fl_bleed', tx: 30, ty: 14, spr: 'board', bleed: 1,
            label: '[E] the wall by the doors',
            text: 'Thirty chairs stacked against this wall, and thirty in a circle inside. That is sixty chairs, in a centre that owns thirty. Somebody is setting out each lot, at the same time, four feet apart, through a wall. Neither of them knows. Both will be done by ten to seven.' },
        ],
        pickups: [
          { id: 'fl_sheet', tx: 14, ty: 11, spr: 'dossier', item: 'sheet',
            name: 'A SIGN-IN SHEET',
            note: 'Thirty-one lines, thirty-one hands, thirty-one names. Not one of them has been struck out. There are four blank lines at the bottom and the pen is still clipped to the board.',
            fact: 'flats_sheet' },
        ],
        npcs: [
          { id: 'iris', name: 'Iris Nakamura', spr: 'iris', tx: 13, ty: 13,
            label: '[E] the woman setting out chairs' },
        ],
        // no Unbilled here. Nothing on this district is billing.
        actors: [],
      },
    },
  },
  {
    id: 'motor',
    name: 'MOTOR ROW',
    ox: 36, oy: 60,
    rows: [
      '#################....###################',
      '#################....###################',
      '#################....###################',
      '#......................................#',
      '#.ooooooooooooo........###############.#',
      '#.o:::::::::::o........###############.#',
      '#.o:::::::::::o........###############.#',
      '#.o:::::::::::o........###############.#',
      '#.o::::::::::::........###############.#',
      '#.o::::::::::::........##wwww###wwww##.#',
      '#.o:::::::::::o........######++#######.#',
      '#.o:::::::::::o........................#',
      '#.ooooooooooooo........................#',
      '#.....T.....T.............T.....T......#',
      '#======================================#',
      '#======================================#',
      '#--------------------------------------#',
      '#======================================#',
      '#.......bb..................bb.........#',
      '#......................................#',
      '#.################....################.#',
      '#.##wwww###wwww###....##wwww###wwww###.#',
      '#.################....################.#',
      '#.################....################.#',
      '#.################....################.#',
      '#.################....################.#',
      '#.####++####++####....####++####++####.#',
      '#......................................#',
      '#..................xx..................#',
      '########################################',
    ],
    layers: {
      street: {
        greet: 'MOTOR ROW. Tow yards, body shops, and the only chiropractor in this city who returns a lawyer\'s call inside the hour.',
        props: [
          { id: 'mr_gate', tx: 15, ty: 8, spr: 'sign', repeat: true, tree: 'lien',
            label: '[E] BONILLA TOWING — gate',
            text: 'BONILLA TOWING & RECOVERY. STORAGE $65/DAY. LIEN SALE AFTER 30. The lien-sale line is the only one on the board that has been repainted, and it has been repainted recently.' },
          { id: 'mr_impound', tx: 8, ty: 8, spr: 'sign', label: '[E] the impound rows',
            text: 'Four rows of cars that stopped being transport and became collateral. Every one of them has a windshield ticket and a story, and in about a third of them the story is that somebody could not find eleven hundred dollars in a week. You know that number.' },
          { id: 'mr_chiro', tx: 29, ty: 11, spr: 'sign', label: '[E] KESTENBAUM CHIROPRACTIC — WALK-INS',
            text: 'KESTENBAUM CHIROPRACTIC — WALK-INS — ABOGADOS WELCOME. That last word is not on the sign. It is on a smaller sign, under the sign.' },
          { id: 'mr_shop', tx: 6, ty: 27, spr: 'board', label: '[E] the body shop, roll-up door open',
            text: 'A tow-truck cab up on the lift with its whole left side folded in — struck square, driver\'s door to the B-pillar, the paint transfer still on it in somebody else\'s colour. Nothing about this is a rear-end. Whoever hit this came across the intersection, and came across it fast.',
            fact: 'dee_liability' },
          { id: 'mr_bench', tx: 28, ty: 19, spr: 'board', label: '[E] the bus bench',
            text: 'A bus bench with a face on it, six feet wide and smiling: HURT? CALL VONNIE. NO FEE UNLESS WE WIN. The face has been up long enough to have faded, and somebody has drawn nothing on it at all, which in this neighbourhood is a form of respect.',
            fact: 'dee_rival' },
          // ---- the bleed ----
          { id: 'mr_bleed', tx: 33, ty: 13, spr: 'board', bleed: 1,
            label: '[E] the car nobody is in',
            text: 'Third from the end, nose out, engine running. Not rough, the way a car left running goes — warm and even, wipers parked, tank full, driver\'s door unlocked. The seat is set for somebody about your height. There is a coffee in the holder, still hot. The ticket on the windshield is dated tomorrow.' },
        ],
        pickups: [
          { id: 'mr_ledger', tx: 19, ty: 24, spr: 'dossier', item: 'ledger',
            name: 'A TREATMENT LEDGER, IN THE ALLEY TRASH',
            note: 'Forty-one patients, all of them somebody\'s plaintiff. The per-visit figure at the bottom is three times what an insurer pays for the same forty minutes.',
            fact: 'kest_lien' },
        ],
        npcs: [
          { id: 'dee', name: 'Dee Ferraro', spr: 'dee', tx: 16, ty: 11,
            label: '[E] the driver outside the yard' },
          { id: 'kestenbaum', name: 'Dr. Kestenbaum', spr: 'kestenbaum', tx: 33, ty: 11,
            label: '[E] the chiropractor' },
        ],
        actors: [
          { id: 'mr_civ1', type: 'civ', tx: 24, ty: 19 },
          { id: 'mr_civ2', type: 'civ', tx: 10, ty: 19 },
          { id: 'mr_srv1', type: 'server', tx: 33, ty: 27 },
          { id: 'mr_chase', type: 'chaser', tx: 31, ty: 3 },
          { id: 'mr_coll1', type: 'collections', tx: 6, ty: 27 },
        ],
      },
      floor: {
        sub: { T: 'x' },
        lightCost: 14,
        greet: 'MOTOR ROW. Every bay is lit and every lift is down and every car on this street is running.',
        greetDark: 'MOTOR ROW. You cannot see the cars. You can hear all of them.',
        props: [
          { id: 'mr_panel', tx: 18, ty: 3, spr: 'board', repeat: true, lights: true,
            label: '[E] the lighting panel',
            text: 'Bolted to the wall at the mouth of the alley, outdoors, in the weather — which it has not had for some time, there being no weather. Same form. Same hand.' },
          { id: 'mr_cars', tx: 8, ty: 8, spr: 'sign', label: '[E] the impound rows',
            text: 'Four rows, and every engine in all four is running. Warm hoods. Wipers parked. One of them has its indicator going, patiently, for a turn out of a lot it has been in for forty years. You put your hand on a tank and it is full, and you take your hand off, and it is still full.',
            fact: 'mr_running' },
          { id: 'mr_ticket', tx: 16, ty: 11, spr: 'board', label: '[E] a windshield ticket',
            text: 'IMPOUNDED — RELEASE ON SIGNATURE ONLY. You check the next one, and the next, and the next row. Same date on all of them. It is the date on every calendar in this building, which is today, which is the day it has been the entire time you have been awake.',
            fact: 'mr_tickets' },
          { id: 'mr_mine', tx: 12, ty: 6, spr: 'sign', label: '[E] the car in the second row',
            text: 'This one is not running. It is the only one. The ticket under the wiper has a name written on it in a hand you have been signing things with your entire adult life, and the date on it is not today. The date on it is tomorrow.',
            fact: 'mr_yours' },
          // ---- the bleed ----
          { id: 'mr_bleed', tx: 33, ty: 13, spr: 'board', bleed: 1,
            label: '[E] the gap in the fourth row',
            text: 'A space in the fourth row the exact size of a car, oil stain still wet at the edges. Every other slot here has been full since before you were born. Somebody signed for one and drove it off the lot. The gate is thirty feet away.' },
        ],
        pickups: [
          { id: 'mr_keys', tx: 19, ty: 24, spr: 'dossier', item: 'keys',
            name: 'A RING OF KEYS, TAGGED', note: 'Forty-odd keys on a ring, each with a paper tag, each tag a matter number. None of them is a car key.',
            fact: 'mr_keyring' },
        ],
        npcs: [
          { id: 'yardman', name: 'The Yard Man', spr: 'yardman', tx: 15, ty: 9,
            label: '[E] the man at the gate' },
        ],
        actors: [
          { id: 'mr_unb1', type: 'unbilled', tx: 26, ty: 19 },
          { id: 'mr_unb2', type: 'unbilled', tx: 10, ty: 27 },
          { id: 'mr_sty1', type: 'stayed', tx: 30, ty: 27 },
        ],
      },
    },
  },
];

// ============================== INSIDE ==============================
// Rooms. Same engine, same global grid, same two layers — an interior is an
// ordinary region that happens to sit in a band of the grid you cannot walk to,
// at `oy: 200`, a hundred and forty tiles below the city and far outside the
// streamer's 44-tile eviction pad. So a room is never resident while you are on
// the street and the street is never resident while you are in a room.
//
// They are spaced 120 tiles apart along the belt for the same reason, and it is
// not tidiness. Two rooms inside LOAD_PAD of each other are BOTH built, and at
// low zoom you see the other one hanging in the void beside you. `tools/check`
// enforces the spacing.
//
// Why a separate region rather than a hole carved in the building: the renderer
// has no roof. A room cut out of a `#` block is on screen from the pavement,
// permanently — you would read Department 13's benches from the newsstand. It
// also caps every room at whatever the exterior footprint happens to allow,
// which is a stupid reason for a room to be the shape it is.
//
// An interior declares:
//   interior  true — the camera clamps to it, and nothing spawns in it
//   of        the district it belongs to. Lighting, bleed and the map read
//             through this, so a room in a lit district is lit
//   at        that district's door tile, which is where the map puts your dot
//
// Doors are authored in PAIRS, `into` + `spot` on both sides, and tools/check
// enforces the pairing exactly the way it enforces a crossing — a door in with
// no door out is the same one-way trip and the same worst bug.
export const INTERIORS = [
  {
    id: 'sublevel',
    name: 'SUBLEVEL C',
    interior: true, of: 'annex', at: [30, 4],
    ox: 480, oy: 200,
    // THE FLOOR ONLY, and the only region in the game with one layer — the
    // deliberate exception DESIGN §9.3 reserves. On THE STREET the chain is
    // still across the stair with its unclosed padlock, which is not a broken
    // promise: it is a chain. On THE FLOOR the chain is on the ground and this
    // is what is at the bottom.
    //
    // Floored in `%`, the same stone as the DC&H atrium, in a building the firm
    // gifted to the county in 1971 subject to clause 9.
    rows: [
      '##############################',
      '#############ss###############',
      '#############ss###############',
      '#%%%%%%%%%%%%%%%%%%%%%%%%%%%%#',
      '#%%%cccccccc%%%%%%cccccccc%%%#',
      '#%%%%%%%%%%%%%%%%%%%%%%%%%%%%#',
      '#%%%cccccccc%%%%%%cccccccc%%%#',
      '#%%%%%%%%%%%%%%%%%%%%%%%%%%%%#',
      '#%%%%%%%%%%%%%%%%%%%%%%%%%%%%#',
      '#%%%%%%%%%%%%%cc%%%%%%%%%%%%%#',
      '#%%%%%%%%%%%%%cc%%%%%%%%%%%%%#',
      '#%%%%%%%%%%%%%%%%%%%%%%%%%%%%#',
      '#%%%%%%%%%%%%%%%%%%%%%%%%%%%%#',
      '#%%%cccccccc%%%%%%cccccccc%%%#',
      '#%%%%%%%%%%%%%%%%%%%%%%%%%%%%#',
      '#%%%cccccccc%%%%%%cccccccc%%%#',
      '#%%%%%%%%%%%%%%%%%%%%%%%%%%%%#',
      '#%%%%%%%%%%%%%%%%%%%%%%%%%%%%#',
      '#%%%%%%%%%%%%%%%%%%%%%%%%%%%%#',
      '##############################',
    ],
    layers: {
      floor: {
        greet: 'SUBLEVEL C. A room the size of the building above it, and the air is warmer down here than it was up there.',
        greetDark: 'SUBLEVEL C, unlit, and the only thing you can hear is running, and it is not going to stop while you decide.',
        props: [
          { id: 'sl_up', tx: 14, ty: 1, spr: 'sign', repeat: true,
            into: 'annex', spot: [30, 5],
            label: '[E] back up the stair',
            text: 'Three flights up, and the air gets colder on the way.' },
          // the matter, at the bottom of the stair that has been describing it
          { id: 'sl_copier', tx: 14, ty: 9, spr: 'sign', repeat: true, tree: 'copier',
            label: '[E] the copier' },
          { id: 'sl_boxes', tx: 6, ty: 4, spr: 'dossier', repeat: true,
            label: '[E] the boxes it is working from',
            text: 'Banker\'s boxes on steel racking, in runs, lids off, and the run nearest the machine has been worked along from left to right — one box pulled forward, emptied, refilled, pushed back, the next one pulled forward. It is about a third of the way down the first run.' },
          { id: 'sl_output', tx: 22, ty: 6, spr: 'dossier', repeat: true,
            label: '[E] the finished side',
            text: 'The other side of the room is what has come off it. Four hundred boxes going in and four hundred coming out, continuously, since 1994, and every sheet of it is somebody\'s work and none of it is wrong. It is not a person and it is not pretending to be one. It is a going concern, and it is still going.',
            fact: 'tf_going' },
          { id: 'sl_door', tx: 27, ty: 18, spr: 'sign', repeat: true,
            label: '[E] the door at the far end',
            text: 'A fire door in the far wall with a push bar on this side and no handle on the other, which means it has opened outwards, from in here, whenever anybody wanted. There is a wedge on the floor beside it that has never been used. Nobody asked anybody to stay.',
            fact: 'tf_nobody' },
          { id: 'sl_stone', tx: 14, ty: 17, spr: 'board',
            label: '[E] the floor',
            text: 'The same stone as the atrium across town, laid the same way, in a building the firm gave to the county in 1971 in perpetuity and subject to clause 9. Somebody specified this for a basement nobody was going to stand in.' },
        ],
        pickups: [
          { id: 'sl_toner', tx: 20, ty: 12, spr: 'dossier', item: 'toner',
            name: 'A TONER ORDER, STANDING',
            note: 'A standing order for toner, quarterly, delivered to a loading dock at an address that has been the county\'s since 1971, paid from an account that is not the county\'s. Last amended 1994.' },
        ],
        actors: [
          { id: 'sl_unb1', type: 'unbilled', tx: 8, ty: 12 },
          { id: 'sl_unb2', type: 'unbilled', tx: 24, ty: 16 },
        ],
      },
    },
  },
  {
    id: 'dept13',
    name: 'DEPARTMENT 13',
    interior: true, of: 'courthouse', at: [19, 11],
    ox: 360, oy: 200,
    // A courtroom, laid out as one: the bench at the top, two counsel tables in
    // the well, the bar across the middle with its gate, the gallery behind it,
    // and a centre aisle running from the doors to the gate.
    //
    // The bar is `|`, which is the whole layer contrast. On THE STREET it is
    // there and you are behind it, because you are not counsel of record on
    // anything being heard. On THE FLOOR it is not there at all, and the room
    // is one twenty-four by thirteen space with nothing between you and the
    // bench, and the caption has your name on both sides.
    rows: [
      '##########################',
      '#________________________#',
      '#________cccccccc________#',
      '#________________________#',
      '#________________________#',
      '#_____cccc______cccc_____#',
      '#________________________#',
      '#________________________#',
      '#|||||||||||__|||||||||||#',
      '#________________________#',
      '#__ccccccccc__ccccccccc__#',
      '#________________________#',
      '#__ccccccccc__ccccccccc__#',
      '#________________________#',
      '#wwwwwwwwwww++wwwwwwwwwww#',
      '##########################',
    ],
    layers: {
      street: {
        greet: 'SUPERIOR COURT, DEPARTMENT 13. The ten oclock calendar, called at twenty past.',
        props: [
          { id: 'd13_out', tx: 12, ty: 14, spr: 'sign', repeat: true,
            into: 'courthouse', spot: [19, 12],
            label: '[E] back out to the steps',
            text: 'Out through the doors, down the steps.' },
          { id: 'd13_bench', tx: 12, ty: 2, spr: 'sign', repeat: true,
            label: '[E] the bench',
            text: 'Hon. M. Bane, presiding, in a robe that has been pressed by somebody who does it every week. He is hearing a motion to compel from a man who has plainly not read his own exhibit, and he is hearing all of it, and he will rule correctly and without pleasure.' },
          { id: 'd13_bar', tx: 12, ty: 7, spr: 'sign', repeat: true,
            label: '[E] the gate in the bar',
            text: 'A swing gate in a wooden rail, eleven inches of it, with a brass plate worn through the lacquer where thirty years of hands have gone over the top of it. You are on the public side. That is not a rule about the gate.' },
          { id: 'd13_calendar', tx: 3, ty: 9, spr: 'board',
            label: '[E] the calendar for the day',
            text: 'Twenty-six matters at ten oclock, in the order the clerk typed them, which is not the order they will be called. Nine are unlawful detainers. Four of the nine have NO APPEARANCE FOR RESPONDENT written in already, in pen, before ten oclock.' },
          { id: 'd13_gallery', tx: 6, ty: 11, spr: 'sign', repeat: true,
            label: '[E] the gallery',
            text: 'Four rows, and everybody in them is here about the thing that is going to happen to them this morning. A woman two along has her file in a supermarket bag. She has read it. You can tell from the edges of it that she has read it more than you have read most of yours.' },
          { id: 'd13_table', tx: 7, ty: 5, spr: 'sign', repeat: true,
            label: '[E] the near counsel table',
            text: 'Two chairs, a jug of water and four glasses upside down on a tray, and a power outlet in the floor under it with a strip of gaffer tape over the socket that says OUT — 2019.' },
        ],
      },
      floor: {
        // no bar. Nothing between you and the bench.
        sub: { '|': '_' },
        greet: 'DEPARTMENT 13. You came in rather than reading the glass.',
        props: [
          { id: 'd13_out', tx: 12, ty: 14, spr: 'sign', repeat: true,
            into: 'courthouse', spot: [19, 12],
            label: '[E] back out to the steps',
            text: 'Out through the doors. The session does not pause while you leave, because it does not pause.' },
          // the matter itself, in the room it has been describing since Phase 3
          { id: 'd13_file', tx: 12, ty: 3, spr: 'dossier', repeat: true, tree: 'dept13',
            label: '[E] the file in front of the bench' },
          { id: 'd13_bar', tx: 12, ty: 8, spr: 'sign', repeat: true,
            label: '[E] where the bar was',
            text: 'There is a line in the boards the width of the room where a rail was taken up, and the holes are still in the floor, and the brass is still bright in them. Nobody stopped at it on the way in, including you, and you did not notice you had not.' },
          { id: 'd13_gallery', tx: 6, ty: 11, spr: 'sign', repeat: true,
            label: '[E] the gallery',
            text: 'Every seat is taken and the room is entirely silent. None of them are waiting to be called. They have all been called. That is what the seats are for.' },
          { id: 'd13_clock', tx: 18, ty: 2, spr: 'board',
            label: '[E] the clock above the bench',
            text: 'Ten past nine. It is a mains clock with a sweep second hand and the second hand is going round, and it has gone round eleven times while you have been looking at it, and it is ten past nine.' },
          { id: 'd13_reporter', tx: 18, ty: 5, spr: 'board',
            label: '[E] the reporter\'s machine',
            text: 'A stenotype on its stand, keys going, tape coming off it in a fold onto the floor. There is nobody at it. The transcript is of what is being argued, and it is accurate, and you check two lines of it against what you have just heard and they match.' },
        ],
      },
    },
  },
  {
    id: 'grabbit',
    name: 'GRABBIT & RUNN',
    interior: true, of: 'tower', at: [31, 11],
    ox: 240, oy: 200,
    // Deliberately the DC&H atrium again, at three-quarter scale and tile for
    // tile: lift doors along the top, the counter across the middle, the glass
    // and the way out at the bottom, the same stone underfoot. `gr_carpet` has
    // said "the same layout" since Phase 3 and nobody could check it. Now the
    // player walks in and checks it.
    rows: [
      '################',
      '#%%||%%%%%%||%%#',
      '#%%%%%%%%%%%%%%#',
      '#%%%%%%%%%%%%%%#',
      '#%%%%cccccc%%%%#',
      '#%%%%%%%%%%%%%%#',
      '#%%%%%%%%%%%%%%#',
      '#%%%%%%%%%%%%%%#',
      '#wwwwww++wwwwww#',
      '################',
    ],
    layers: {
      street: {
        greet: 'GRABBIT & RUNN. You have been in this room before. You have never been in this room.',
        props: [
          { id: 'gr_out', tx: 7, ty: 8, spr: 'sign', repeat: true,
            into: 'tower', spot: [31, 12],
            label: '[E] back out to the plaza',
            text: 'Out, across the plaza, past the other set of doors.' },
          // the matter itself, moved off the plaza and into the room it has
          // been describing since Phase 3
          { id: 'gr_desk', tx: 7, ty: 4, spr: 'sign', repeat: true, tree: 'grabbit',
            label: '[E] reception' },
          { id: 'gr_chairs', tx: 12, ty: 6, spr: 'sign', repeat: true,
            label: '[E] the chairs',
            text: 'Four chairs at right angles to each other, and a low table with the firm\'s own publications on it: a client bulletin on changes to the limitation period, and a glossy about the pro bono programme with a photograph of eleven people in a food bank.' },
          { id: 'gr_photo', tx: 3, ty: 2, spr: 'board',
            label: '[E] the photograph on the wall',
            text: 'A photograph of the building at dusk with every window lit, blown up to four feet. There is one at DC&H of the other building, at dusk, with every window lit, blown up to four feet, and you have walked past it eleven hundred times.' },
          { id: 'gr_lifts', tx: 11, ty: 1, spr: 'sign', repeat: true,
            label: '[E] the lift bank',
            text: 'Four lifts and a card reader on the wall between the second and the third, at the height the reader is at across the plaza, in the finish the reader is in across the plaza.' },
        ],
      },
      floor: {
        sub: { '|': '%' },
        greet: 'GRABBIT & RUNN. The same room. Not similar — the same, and the folder is already on the counter.',
        greetDark: 'GRABBIT & RUNN, unlit, and you cross it without putting a hand out, because you know where the counter is.',
        props: [
          { id: 'gr_out', tx: 7, ty: 8, spr: 'sign', repeat: true,
            into: 'tower', spot: [31, 12],
            label: '[E] back out to the plaza',
            text: 'Out through the doors. They open outwards on this side too.' },
          { id: 'gr_folder', tx: 7, ty: 4, spr: 'dossier', repeat: true,
            label: '[E] the folder on the counter',
            text: 'A folder, made up, your name spelled correctly on the tab. Inside: of counsel, a floor, a salary with a comma in it, and the covenant bought out on your first day. The date on the covering letter is the Thursday you resigned, and it was typed before lunch.',
            fact: 'gr_same' },
          { id: 'gr_photo', tx: 3, ty: 2, spr: 'board',
            label: '[E] the photograph on the wall',
            text: 'The building at dusk with every window lit. You have been in both of these rooms tonight and you could not now say which one you are in, and the photograph is not going to settle it, because the photograph is of the other one from here and of this one from there.' },
          { id: 'gr_chairs', tx: 12, ty: 6, spr: 'sign', repeat: true,
            label: '[E] the chairs',
            text: 'Four chairs at right angles. The one facing the counter has been sat in recently enough that the cushion has not come back up, and it comes back up while you are looking at it.' },
          { id: 'gr_lifts', tx: 11, ty: 1, spr: 'sign', repeat: true,
            label: '[E] the lifts standing open',
            text: 'Four lifts, all open, all lit. The panel in each one has the same buttons as the panel across the plaza, including the floors the building does not have, and including the one at the bottom with no number on it.' },
        ],
        actors: [
          { id: 'gr_sty1', type: 'stayed', tx: 4, ty: 6 },
        ],
      },
    },
  },
  {
    id: 'dch',
    name: 'DEWEY, CHEATHAM & HOWE',
    interior: true, of: 'tower', at: [12, 13],
    ox: 120, oy: 200,
    // Twenty by nine of nothing, which is the whole point of it. The atrium is
    // not big because the firm needs the room; it is big because you are meant
    // to cross it on foot while somebody watches. `%` is stone rather than the
    // boards Suite 2B is floored in: the paint class IS the material, so a
    // lobby stops feeling like your office without a per-room palette. The `|`
    // row is the lift doors — shut on THE STREET, standing open on THE FLOOR.
    rows: [
      '######################',
      '#%%||%%%%%||%%%%%||%%#',
      '#%%%%%%%%%%%%%%%%%%%%#',
      '#%%%%%%%%%%%%%%%%%%%%#',
      '#%%%%%%%%%%%%%%%%%%%%#',
      '#%%%%%%ccccccc%%%%%%%#',
      '#%%%%%%%%%%%%%%%%%%%%#',
      '#%%%%%%%%%%%%%%%%%%%%#',
      '#%%%%%%%%%%%%%%%%%%%%#',
      '#%%%%%%%%%%%%%%%%%%%%#',
      '#wwwwwwwww++wwwwwwwww#',
      '######################',
    ],
    layers: {
      street: {
        greet: 'DEWEY, CHEATHAM & HOWE. Nine years of mornings. The floor is the same floor.',
        props: [
          { id: 'dc_out', tx: 10, ty: 10, spr: 'sign', repeat: true,
            into: 'tower', spot: [12, 14],
            label: '[E] back out to the plaza',
            text: 'Out through the doors, down the steps.' },
          { id: 'dc_board', tx: 4, ty: 3, spr: 'board', repeat: true,
            label: '[E] the directory board',
            text: 'Cut vinyl on black felt, floors 3 to 19, practice groups in caps and partners under them in title case. Your name came off the eleventh floor on a Thursday. The felt where it was has not faded like the felt around it, so the shape of it is still there, at the right height, in the light.',
            fact: 'dch_board' },
          { id: 'dc_lifts', tx: 10, ty: 1, spr: 'sign', repeat: true,
            label: '[E] the lift bank',
            text: 'Six lifts, and a card reader on the wall between the third and the fourth. You handed the card back at the desk downstairs on your last morning and watched a woman you had never met put it in a drawer with about forty others.' },
          { id: 'dc_desk', tx: 10, ty: 5, spr: 'sign', repeat: true,
            label: '[E] the visitors\' book',
            text: 'A visitors\' book, turned to face out, and a pen on a chain. NAME, FIRM, WHOM VISITING, IN, OUT. Nobody has filled in an OUT since the fourteenth.' },
          { id: 'dc_licence', tx: 17, ty: 9, spr: 'board',
            label: '[E] what is posted by the door',
            text: 'The things a firm has to post where they can be read, in a frame, at the height of nobody: the licence, the trust-account certification, the notice about fee disputes, and a card giving the number of the bar\'s complaint line. The card is the only one that has been touched.' },
        ],
        npcs: [
          { id: 'dcguard', name: 'Ray Okafor', spr: 'clerk', tx: 10, ty: 6,
            label: '[E] the man on the desk' },
        ],
      },
      floor: {
        // the lifts are open on this side
        sub: { '|': '%' },
        greet: 'DEWEY, CHEATHAM & HOWE. The lights are on in the atrium and the lifts are standing open.',
        greetDark: 'DEWEY, CHEATHAM & HOWE. You cross it from memory. You have crossed it from memory before, in the dark, at this hour, awake.',
        props: [
          { id: 'dc_out', tx: 10, ty: 10, spr: 'sign', repeat: true,
            into: 'tower', spot: [12, 14],
            label: '[E] back out to the plaza',
            text: 'Out through the doors. They open outwards and they do not resist.' },
          { id: 'dc_board', tx: 4, ty: 3, spr: 'board', repeat: true,
            label: '[E] the directory board',
            text: 'Every name is on it. Yours is on it, on eleven, where it was. The floors run 3 to 19 and then keep going: 20, 21, 24, 31, and a group at the bottom with no number beside it at all, headed RETAINED.',
            fact: 'dch_retained' },
          { id: 'dc_lifts', tx: 10, ty: 1, spr: 'sign', repeat: true,
            label: '[E] the lift standing open',
            text: 'One lift is open and lit and has been for some time. The call button is already pressed. Inside, the panel has a button for every floor on the board, including the ones the board has that the building does not.' },
          { id: 'dc_book', tx: 10, ty: 5, spr: 'sign', repeat: true,
            label: '[E] the visitors\' book',
            text: 'The book is full. Every line is the same hand, and the hand is yours, and the IN times run from 06:40 to 07:15 for four hundred pages. The OUT column has never been filled in.',
            fact: 'dch_signedin' },
          { id: 'dc_chair', tx: 15, ty: 7, spr: 'board',
            label: '[E] the chair by the window',
            text: 'A chair pulled away from the wall and turned to face the doors, at the angle somebody sits at when they are waiting for one particular person. There is a coat over the back of it. It is your coat, and it is the one you were wearing.' },
        ],
        pickups: [
          { id: 'dc_pass', tx: 6, ty: 7, spr: 'dossier', item: 'pass',
            name: 'A BUILDING PASS, STILL LIVE',
            note: 'Your photograph, your name, and an expiry four years after you handed it back. The magnetic strip is worn the way a card gets worn by being used.' },
        ],
        actors: [
          { id: 'dc_sty1', type: 'stayed', tx: 17, ty: 3 },
        ],
      },
    },
  },
  {
    id: 'suite2b',
    name: 'SUITE 2B',
    interior: true, of: 'strand', at: [17, 17],
    ox: 0, oy: 200,
    // Twelve by six, which is the room the writing has always described: a
    // folding table, a cot, and one window. The `|` at the back is a wall on
    // THE STREET and floor on THE FLOOR, so the room you rent is six deep and
    // the room in the other version of it is nine, in a building that is six.
    rows: [
      '##############',
      '#ww####www####',
      '#____________#',
      '#_c__________#',
      '#____________#',
      '#__________cc#',
      '#____________#',
      '+ss__________#',
      '#||||||||||||#',
      '#||||||||||||#',
      '#||||||||||||#',
      '##############',
    ],
    layers: {
      street: {
        greet: 'SUITE 2B. Eleven hundred a week, one window, and the smell of the Wok comes up through the floor.',
        props: [
          { id: 's2_out', tx: 0, ty: 7, spr: 'sign', repeat: true,
            into: 'strand', spot: [17, 18],
            label: '[E] back down the stairs',
            text: 'Down the stairs, past the smell, to the street.' },
          { id: 's2_desk', tx: 2, ty: 3, spr: 'sign', repeat: true, office: true,
            label: '[E] the folding table',
            text: 'A folding table, a lamp, and a chair that came with the room. The day ends here. So does everything else.' },
          { id: 's2_cot', tx: 11, ty: 5, spr: 'sign', repeat: true, notUpgrade: 'bed',
            label: '[E] the cot',
            text: 'A cot you have decided not to describe as a cot. It folds. You have never folded it.' },
          { id: 's2_bed', tx: 11, ty: 5, spr: 'sign', repeat: true, needsUpgrade: 'bed',
            label: '[E] the bed',
            text: 'A bed, made, which the cot never was. The cot went out to the kerb on a Tuesday and was gone by the evening.' },
          { id: 's2_chair', tx: 4, ty: 3, spr: 'sign', repeat: true, needsUpgrade: 'chair',
            label: '[E] the second chair',
            text: 'The second chair, and a phone on the table beside it that rings. Somebody could sit here. Somebody does.' },
          { id: 's2_vinyl', tx: 1, ty: 6, spr: 'sign', repeat: true, needsUpgrade: 'door',
            label: '[E] your name, in vinyl',
            text: 'Your name on the glass in cut vinyl, reading backwards from in here. The masking tape came off the buzzer the same afternoon.' },
          { id: 's2_window', tx: 7, ty: 2, spr: 'board', repeat: true,
            label: '[E] the window over the Strand',
            text: 'The window looks down on the block: the laundromat, the corkboard, the two benches, the storefront that has been PERMANENTLY CLOSED for six years. You can see your own doorway from up here, and the people who walk past it.' },
          { id: 's2_lease', tx: 3, ty: 2, spr: 'board',
            label: '[E] the copy of the lease',
            text: 'Your copy of the lease, on the table where you left it. Eleven hundred a week, payable Fridays, and a clause about the stairwell being common. Signed by somebody at Golden Wok Holdings whose name is a stamp.',
            fact: 'lease_terms' },
        ],
      },
      floor: {
        // the back wall is not there on this side
        sub: { '|': '_' },
        greet: 'SUITE 2B. The door was open. The room goes back further than the building does.',
        greetDark: 'SUITE 2B, in the dark. You know where the table is. The room past it does not sound like six feet.',
        props: [
          { id: 's2_out', tx: 0, ty: 7, spr: 'sign', repeat: true,
            into: 'strand', spot: [17, 18],
            label: '[E] back down the stairs',
            text: 'Down the stairs. The smell of the Wok is not on this side and the stairwell is the same length anyway.' },
          { id: 's2_tape', tx: 1, ty: 6, spr: 'sign', repeat: true,
            label: '[E] the tape on the inside of the glass',
            text: 'Your name on the buzzer tape, yellow and curling. In this version you never resigned and never rented it.',
            fact: 'unsent_drawer' },
          { id: 's2_desks', tx: 6, ty: 4, spr: 'board',
            label: '[E] the desks',
            text: 'Desks, in rows, where the folding table is on the other side. They go back past where the wall is. You count eleven and stop, because the eleventh is against nothing.' },
          { id: 's2_drawer1', tx: 3, ty: 9, spr: 'board',
            label: '[E] the nearest drawer',
            text: 'A letter, drafted, signed, addressed, stamped. Not sent. The date on it is a Thursday you remember.' },
          { id: 's2_drawer2', tx: 8, ty: 10, spr: 'board',
            label: '[E] the next drawer',
            text: 'The same. So is the one under it. Every drawer in this room has a letter in it and none of them have been sent. The handwriting stops being yours somewhere around the fourth.' },
          { id: 's2_drawer3', tx: 11, ty: 10, spr: 'board',
            label: '[E] the last drawer you open',
            text: 'This one is addressed to the Strand. To the building. To Suite 2B. Your name is in the return corner and the postmark is four years out.' },
          { id: 's2_win', tx: 7, ty: 2, spr: 'board', repeat: true,
            label: '[E] the window over the Strand',
            text: 'The window looks down on the block, and the block is lit, and nothing on it moves. The bench you can see from here has somebody on it who has been there as long as you have been at the table.' },
        ],
        pickups: [
          { id: 's2_unsent', tx: 6, ty: 9, spr: 'dossier', item: 'unsent',
            name: 'A LETTER, NOT SENT', note: 'Yours, drafted, stamped, and in a drawer for four years.' },
        ],
      },
    },
  },
];

/** Districts and the rooms inside them — everything the streamer holds. */
export const ALL_REGIONS = [...REGIONS, ...INTERIORS];

// Where each path starts. Both are on the same street, forty tiles apart.
export const SPAWN = {
  street: { x: 82 * 40 + 20, y: 49 * 40 + 20 },   // The Strand, outside your own door
  floor: { x: 56 * 40 + 20, y: 48 * 40 + 20 },   // Courthouse Square, under Dept. 13
};
